package com.wbg.logistics.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_id
     *
     * @mbg.generated
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_account
     *
     * @mbg.generated
     */
    private String aAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_password
     *
     * @mbg.generated
     */
    private String aPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_rank
     *
     * @mbg.generated
     */
    private String aRank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_id
     *
     * @return the value of admin.a_id
     *
     * @mbg.generated
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_id
     *
     * @param aId the value for admin.a_id
     *
     * @mbg.generated
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_account
     *
     * @return the value of admin.a_account
     *
     * @mbg.generated
     */
    public String getaAccount() {
        return aAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_account
     *
     * @param aAccount the value for admin.a_account
     *
     * @mbg.generated
     */
    public void setaAccount(String aAccount) {
        this.aAccount = aAccount == null ? null : aAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_password
     *
     * @return the value of admin.a_password
     *
     * @mbg.generated
     */
    public String getaPassword() {
        return aPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_password
     *
     * @param aPassword the value for admin.a_password
     *
     * @mbg.generated
     */
    public void setaPassword(String aPassword) {
        this.aPassword = aPassword == null ? null : aPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_rank
     *
     * @return the value of admin.a_rank
     *
     * @mbg.generated
     */
    public String getaRank() {
        return aRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_rank
     *
     * @param aRank the value for admin.a_rank
     *
     * @mbg.generated
     */
    public void setaRank(String aRank) {
        this.aRank = aRank == null ? null : aRank.trim();
    }
}