package com.wbg.logistics.entity;

public class Diaodu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diaodu.dis_id
     *
     * @mbg.generated
     */
    private Integer disId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diaodu.staff_no
     *
     * @mbg.generated
     */
    private Integer staffNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diaodu.license
     *
     * @mbg.generated
     */
    private String license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diaodu.waybill_no
     *
     * @mbg.generated
     */
    private String waybillNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diaodu.dis_id
     *
     * @return the value of diaodu.dis_id
     *
     * @mbg.generated
     */
    public Integer getDisId() {
        return disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diaodu.dis_id
     *
     * @param disId the value for diaodu.dis_id
     *
     * @mbg.generated
     */
    public void setDisId(Integer disId) {
        this.disId = disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diaodu.staff_no
     *
     * @return the value of diaodu.staff_no
     *
     * @mbg.generated
     */
    public Integer getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diaodu.staff_no
     *
     * @param staffNo the value for diaodu.staff_no
     *
     * @mbg.generated
     */
    public void setStaffNo(Integer staffNo) {
        this.staffNo = staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diaodu.license
     *
     * @return the value of diaodu.license
     *
     * @mbg.generated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diaodu.license
     *
     * @param license the value for diaodu.license
     *
     * @mbg.generated
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diaodu.waybill_no
     *
     * @return the value of diaodu.waybill_no
     *
     * @mbg.generated
     */
    public String getWaybillNo() {
        return waybillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diaodu.waybill_no
     *
     * @param waybillNo the value for diaodu.waybill_no
     *
     * @mbg.generated
     */
    public void setWaybillNo(String waybillNo) {
        this.waybillNo = waybillNo == null ? null : waybillNo.trim();
    }
}