package com.wbg.logistics.entity;

public class Dispatch {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatch.depart_no
     *
     * @mbg.generated
     */
    private Integer departNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatch.depart_name
     *
     * @mbg.generated
     */
    private String departName;

    public Dispatch(Integer departNo, String departName) {
        this.departNo = departNo;
        this.departName = departName;
    }

    public Dispatch() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatch.depart_no
     *
     * @return the value of dispatch.depart_no
     *
     * @mbg.generated
     */
    public Integer getDepartNo() {
        return departNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatch.depart_no
     *
     * @param departNo the value for dispatch.depart_no
     *
     * @mbg.generated
     */
    public void setDepartNo(Integer departNo) {
        this.departNo = departNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dispatch.depart_name
     *
     * @return the value of dispatch.depart_name
     *
     * @mbg.generated
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dispatch.depart_name
     *
     * @param departName the value for dispatch.depart_name
     *
     * @mbg.generated
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }
}