package com.wbg.logistics.entity;

import java.util.Date;

public class Infro {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infro.infro_id
     *
     * @mbg.generated
     */
    private Integer infroId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infro.i_time
     *
     * @mbg.generated
     */
    private Date iTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infro.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infro.contents
     *
     * @mbg.generated
     */
    private String contents;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infro.infro_id
     *
     * @return the value of infro.infro_id
     *
     * @mbg.generated
     */
    public Integer getInfroId() {
        return infroId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infro.infro_id
     *
     * @param infroId the value for infro.infro_id
     *
     * @mbg.generated
     */
    public void setInfroId(Integer infroId) {
        this.infroId = infroId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infro.i_time
     *
     * @return the value of infro.i_time
     *
     * @mbg.generated
     */
    public Date getiTime() {
        return iTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infro.i_time
     *
     * @param iTime the value for infro.i_time
     *
     * @mbg.generated
     */
    public void setiTime(Date iTime) {
        this.iTime = iTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infro.title
     *
     * @return the value of infro.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infro.title
     *
     * @param title the value for infro.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infro.contents
     *
     * @return the value of infro.contents
     *
     * @mbg.generated
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infro.contents
     *
     * @param contents the value for infro.contents
     *
     * @mbg.generated
     */
    public void setContents(String contents) {
        this.contents = contents == null ? null : contents.trim();
    }
}