package com.wbg.logistics.entity;

public class Route {

    private Depart depart;

    @Override
    public String toString() {
        return "Route{" +
                "depart=" + depart +
                ", routeNo=" + routeNo +
                ", routeName='" + routeName + '\'' +
                ", staffNo=" + staffNo +
                '}';
    }

    public Depart getDepart() {
        return depart;
    }

    public void setDepart(Depart depart) {
        this.depart = depart;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.route_no
     *
     * @mbg.generated
     */
    private Integer routeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.route_name
     *
     * @mbg.generated
     */
    private String routeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.staff_no
     *
     * @mbg.generated
     */
    private Integer staffNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.route_no
     *
     * @return the value of route.route_no
     *
     * @mbg.generated
     */
    public Integer getRouteNo() {
        return routeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.route_no
     *
     * @param routeNo the value for route.route_no
     *
     * @mbg.generated
     */
    public void setRouteNo(Integer routeNo) {
        this.routeNo = routeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.route_name
     *
     * @return the value of route.route_name
     *
     * @mbg.generated
     */
    public String getRouteName() {
        return routeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.route_name
     *
     * @param routeName the value for route.route_name
     *
     * @mbg.generated
     */
    public void setRouteName(String routeName) {
        this.routeName = routeName == null ? null : routeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.staff_no
     *
     * @return the value of route.staff_no
     *
     * @mbg.generated
     */
    public Integer getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.staff_no
     *
     * @param staffNo the value for route.staff_no
     *
     * @mbg.generated
     */
    public void setStaffNo(Integer staffNo) {
        this.staffNo = staffNo;
    }
}