package com.wbg.logistics.entity;

public class Waybill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.waybill_no
     *
     * @mbg.generated
     */
    private String waybillNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_pro
     *
     * @mbg.generated
     */
    private String sPro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_city
     *
     * @mbg.generated
     */
    private String sCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.e_pro
     *
     * @mbg.generated
     */
    private String ePro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.e_city
     *
     * @mbg.generated
     */
    private String eCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_name
     *
     * @mbg.generated
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_phone
     *
     * @mbg.generated
     */
    private String sPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_address
     *
     * @mbg.generated
     */
    private String sAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.r_name
     *
     * @mbg.generated
     */
    private String rName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.r_phone
     *
     * @mbg.generated
     */
    private String rPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.r_address
     *
     * @mbg.generated
     */
    private String rAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.waybill_no
     *
     * @return the value of waybill.waybill_no
     *
     * @mbg.generated
     */
    public String getWaybillNo() {
        return waybillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.waybill_no
     *
     * @param waybillNo the value for waybill.waybill_no
     *
     * @mbg.generated
     */
    public void setWaybillNo(String waybillNo) {
        this.waybillNo = waybillNo == null ? null : waybillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.number
     *
     * @return the value of waybill.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.number
     *
     * @param number the value for waybill.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.unit
     *
     * @return the value of waybill.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.unit
     *
     * @param unit the value for waybill.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_pro
     *
     * @return the value of waybill.s_pro
     *
     * @mbg.generated
     */
    public String getsPro() {
        return sPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_pro
     *
     * @param sPro the value for waybill.s_pro
     *
     * @mbg.generated
     */
    public void setsPro(String sPro) {
        this.sPro = sPro == null ? null : sPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_city
     *
     * @return the value of waybill.s_city
     *
     * @mbg.generated
     */
    public String getsCity() {
        return sCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_city
     *
     * @param sCity the value for waybill.s_city
     *
     * @mbg.generated
     */
    public void setsCity(String sCity) {
        this.sCity = sCity == null ? null : sCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.e_pro
     *
     * @return the value of waybill.e_pro
     *
     * @mbg.generated
     */
    public String getePro() {
        return ePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.e_pro
     *
     * @param ePro the value for waybill.e_pro
     *
     * @mbg.generated
     */
    public void setePro(String ePro) {
        this.ePro = ePro == null ? null : ePro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.e_city
     *
     * @return the value of waybill.e_city
     *
     * @mbg.generated
     */
    public String geteCity() {
        return eCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.e_city
     *
     * @param eCity the value for waybill.e_city
     *
     * @mbg.generated
     */
    public void seteCity(String eCity) {
        this.eCity = eCity == null ? null : eCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_name
     *
     * @return the value of waybill.s_name
     *
     * @mbg.generated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_name
     *
     * @param sName the value for waybill.s_name
     *
     * @mbg.generated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_phone
     *
     * @return the value of waybill.s_phone
     *
     * @mbg.generated
     */
    public String getsPhone() {
        return sPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_phone
     *
     * @param sPhone the value for waybill.s_phone
     *
     * @mbg.generated
     */
    public void setsPhone(String sPhone) {
        this.sPhone = sPhone == null ? null : sPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_address
     *
     * @return the value of waybill.s_address
     *
     * @mbg.generated
     */
    public String getsAddress() {
        return sAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_address
     *
     * @param sAddress the value for waybill.s_address
     *
     * @mbg.generated
     */
    public void setsAddress(String sAddress) {
        this.sAddress = sAddress == null ? null : sAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.r_name
     *
     * @return the value of waybill.r_name
     *
     * @mbg.generated
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.r_name
     *
     * @param rName the value for waybill.r_name
     *
     * @mbg.generated
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.r_phone
     *
     * @return the value of waybill.r_phone
     *
     * @mbg.generated
     */
    public String getrPhone() {
        return rPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.r_phone
     *
     * @param rPhone the value for waybill.r_phone
     *
     * @mbg.generated
     */
    public void setrPhone(String rPhone) {
        this.rPhone = rPhone == null ? null : rPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.r_address
     *
     * @return the value of waybill.r_address
     *
     * @mbg.generated
     */
    public String getrAddress() {
        return rAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.r_address
     *
     * @param rAddress the value for waybill.r_address
     *
     * @mbg.generated
     */
    public void setrAddress(String rAddress) {
        this.rAddress = rAddress == null ? null : rAddress.trim();
    }
}