package com.wbg.logistics.dao;

import com.wbg.logistics.entity.Depart;
import com.wbg.logistics.entity.Dispatch;

import java.util.List;

public interface DepartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer staffNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    int insert(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    List<Depart> selectByPrimaryKey(Integer staffNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    List<Depart> selectAll();
    List<Depart> selectAllJson();
    List<Depart> selectByType(String staffName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Depart record);
}