package com.wbg.logistics.dao;

import com.wbg.logistics.entity.Diaodu;
import java.util.List;

public interface DiaoduMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diaodu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer disId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diaodu
     *
     * @mbg.generated
     */
    int insert(Diaodu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diaodu
     *
     * @mbg.generated
     */
    Diaodu selectByPrimaryKey(Integer disId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diaodu
     *
     * @mbg.generated
     */
    List<Diaodu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diaodu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Diaodu record);
}