package com.wbg.logistics.dao;

import com.wbg.logistics.entity.Dispatch;
import java.util.List;

public interface DispatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer departNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbg.generated
     */
    int insert(Dispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbg.generated
     */
    Dispatch selectByPrimaryKey(Integer departNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbg.generated
     */
    List<Dispatch> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dispatch record);


}