package com.wbg.logistics.dao;

import com.wbg.logistics.entity.Firm;
import java.util.List;

public interface FirmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer firmNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbg.generated
     */
    int insert(Firm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbg.generated
     */
    Firm selectByPrimaryKey(Integer firmNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbg.generated
     */
    List<Firm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Firm record);
}