package com.wbg.logistics.dao;

import com.wbg.logistics.entity.Infro;
import java.util.List;

public interface InfroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infro
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer infroId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infro
     *
     * @mbg.generated
     */
    int insert(Infro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infro
     *
     * @mbg.generated
     */
    Infro selectByPrimaryKey(Integer infroId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infro
     *
     * @mbg.generated
     */
    List<Infro> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infro
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Infro record);
}