package com.wbg.logistics.dao;

import com.wbg.logistics.entity.Positions;
import java.util.List;

public interface PositionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table positions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer posId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table positions
     *
     * @mbg.generated
     */
    int insert(Positions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table positions
     *
     * @mbg.generated
     */
    Positions selectByPrimaryKey(Integer posId);
    List<Positions> selectBywaybillNo(String waybillNo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table positions
     *
     * @mbg.generated
     */
    List<Positions> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table positions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Positions record);
}