package com.wbg.logistics.dao;

import com.wbg.logistics.entity.Route;

import java.lang.reflect.Parameter;
import java.util.List;

public interface RouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer routeNo);
    List<Route> selectByName(String routeName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int insert(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    List<Route> selectByPrimaryKey(Integer routeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    List<Route> selectAll();
    List<Route> selectAllJson();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Route record);
}