package com.wbg.logistics.dao;

import com.wbg.logistics.entity.Waybill;
import java.util.List;

public interface WaybillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String waybillNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int insert(Waybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    List<Waybill> selectByPrimaryKey(String waybillNo);
    List<Waybill> selectsPhonesele(String sPhonesele);
    List<Waybill> selectrPhonesele(String rPhonesele);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    List<Waybill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Waybill record);
}